### ISSUE TITLE
Getting lot of errors after running npm install

### ISSUE THREAD

**Issue by yashwanthkata** [ng-book/angular2-rxjs-chat#23]
pm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\Program Files (x86)\nodejs\node.exe" "C:\..\..\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js" "install"
npm ERR! node v6.2.2
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
                                                                                npm ERR! node-sass@3.4.2 postinstall: `node scripts/build.js`
npm ERR! Exit status 1                                                          npm ERR!
npm ERR! Failed at the node-sass@3.4.2 postinstall script 'node scripts/build.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.    npm ERR! If you do, this is most likely a problem with the node-sass package,
npm ERR! not with npm itself.                                                   npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/build.js                                              npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-sass
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-sass                                             npm ERR! There is likely additional logging output above.
                                                                                npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users..\Documents\Chat\Chat Git\npm-debug.log

**Comment by hamisterbr** [comment]
Do you solve the problems ? i'm having the same ...

**Comment by miguelangelgsl** [comment]
Same problem

**Comment by Zavael** [comment]
I had the same but after updating node and npm I got other errors with python <3.0.0 missing, I have python 3.3.2, but there were no requirements on python version. The erros:

```
gyp info using node-gyp@3.4.0
gyp info using node@6.6.0 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\Development\projects\js\temp\angular2-rxjs-chat\node_modules\which\which.js:14:12)
gyp verb `which` failed     at F (C:\Development\projects\js\temp\angular2-rxjs-chat\node_modules\which\which.js:69:19)
gyp verb `which` failed     at E (C:\Development\projects\js\temp\angular2-rxjs-chat\node_modules\which\which.js:81:29)
gyp verb `which` failed     at C:\Development\projects\js\temp\angular2-rxjs-chat\node_modules\which\which.js:90:16
gyp verb `which` failed     at C:\Development\projects\js\temp\angular2-rxjs-chat\node_modules\isexe\index.js:44:5
gyp verb `which` failed     at C:\Development\projects\js\temp\angular2-rxjs-chat\node_modules\isexe\windows.js:29:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:123:15)
gyp verb `which` failed  python2 { Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\Development\projects\js\temp\angular2-rxjs-chat\node_modules\which\which.js:14:12)
gyp verb `which` failed     at F (C:\Development\projects\js\temp\angular2-rxjs-chat\node_modules\which\which.js:69:19)
gyp verb `which` failed     at E (C:\Development\projects\js\temp\angular2-rxjs-chat\node_modules\which\which.js:81:29)
gyp verb `which` failed     at C:\Development\projects\js\temp\angular2-rxjs-chat\node_modules\which\which.js:90:16
gyp verb `which` failed     at C:\Development\projects\js\temp\angular2-rxjs-chat\node_modules\isexe\index.js:44:5
gyp verb `which` failed     at C:\Development\projects\js\temp\angular2-rxjs-chat\node_modules\isexe\windows.js:29:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:123:15) code: 'ENOENT' }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` succeeded python C:\Program Files (x86)\Python33\python.EXE
gyp verb check python version `C:\Program Files (x86)\Python33\python.EXE -c "import platform; print(platform.python_version());"` returned: "3.3.2\r\n"
gyp ERR! configure error
gyp ERR! stack Error: Python executable "C:\Program Files (x86)\Python33\python.EXE" is v3.3.2, which is not supported by gyp.
```

**Comment by jashmenn** [comment]
I've removed `node-sass` as a dependency and I'm just compiling the sass ahead of time now, so this shouldn't be necessary
