### ISSUE TITLE
Problem running chat app

### ISSUE THREAD

**Issue by vzairovlogi** [ng-book/angular2-rxjs-chat#26]
Hello I have this error and I can't find the way to make it work. If you have any suggestions, I would really appreciate it. Thanks!

`112055242NB004:angular2-rxjs-chat valilogi$ npm run go

> angular2-rxjs-chat@1.0.0 go /Users/valilogi/GitHub/angular/angular2-rxjs-chat
> webpack-dev-server --display-reasons --display-chunks

{ cache: true,
  debug: true,
  verbose: true,
  displayErrorDetails: true,
  displayReasons: true,
  displayChunks: true,
  context: '/Users/valilogi/GitHub/angular/angular2-rxjs-chat',
  entry: 
   { vendor: './app/ts/vendor.ts',
     app: 
      [ 'webpack-dev-server/client?http://0.0.0.0:8080',
        './app/ts/app.ts' ] },
  stats: { colors: true, reasons: true },
  devtool: 'source-map',
  recordsPath: '/Users/valilogi/GitHub/angular/angular2-rxjs-chat/.webpack.json',
  devServer: 
   { inline: true,
     colors: true,
     contentBase: '/Users/valilogi/GitHub/angular/angular2-rxjs-chat/build',
     publicPath: '/' },
  output: 
   { path: '/Users/valilogi/GitHub/angular/angular2-rxjs-chat/build',
     filename: '[name].js',
     publicPath: '/',
     chunkFilename: '[id].bundle.js',
     hotUpdateMainFilename: 'updates/[hash].update.json',
     hotUpdateChunkFilename: 'updates/[hash].[id].update.js' },
  plugins: 
   [ IgnorePlugin { resourceRegExp: /spec\.js$/, contextRegExp: undefined },
     CommonsChunkPlugin {
       chunkNames: 'vendor',
       filenameTemplate: 'vendor.js',
       minChunks: Infinity,
       selectedChunks: undefined,
       async: undefined,
       minSize: undefined,
       ident: '/Users/valilogi/GitHub/angular/angular2-rxjs-chat/node_modules/webpack/lib/optimize/CommonsChunkPlugin.js0' },
     CommonsChunkPlugin {
       chunkNames: 'common',
       filenameTemplate: 'common.js',
       minChunks: 2,
       selectedChunks: [ 'app', 'vendor' ],
       async: undefined,
       minSize: undefined,
       ident: '/Users/valilogi/GitHub/angular/angular2-rxjs-chat/node_modules/webpack/lib/optimize/CommonsChunkPlugin.js1' },
     ExtractTextPlugin { filename: 'styles.css', options: {}, id: 1 },
     DefinePlugin { definitions: { VERSION: '"1.0.0"', ENV: undefined } },
     HtmlWebpackPlugin {
       options: { template: '/Users/valilogi/GitHub/angular/angular2-rxjs-chat/app/index.html' } },
     WebpackReloadPlugin { ip: 'localhost' },
     { options: { title: 'ng-book' }, lastBuildSucceeded: false } ],
  resolveLoader: 
   { root: '/Users/valilogi/GitHub/angular/angular2-rxjs-chat/node_modules',
     modulesDirectories: [ 'node_modules' ],
     fallback: '/Users/valilogi/GitHub/angular/angular2-rxjs-chat/node_modules' },
  resolve: 
   { root: [ '/Users/valilogi/GitHub/angular/angular2-rxjs-chat' ],
     modulesDirectories: [ 'node_modules', 'app', 'app/ts', '.' ],
     extensions: [ '', '.ts', '.js', '.json', '.css' ],
     alias: 
      { app: 'app',
        scripts: '/Users/valilogi/GitHub/angular/angular2-rxjs-chat/node_modules' } },
  module: 
   { preLoaders: [ { test: /\.ts$/, loader: 'tslint' } ],
     loaders: 
      [ { test: /\.(png|jpg|gif)$/,
          loader: 'url-loader?limit=50000&name=[path][name].[ext]' },
        { test: /\.json$/, loader: 'json' },
        { test: /^(?!.*\.min\.css$).*\.css$/,
          loader: '/Users/valilogi/GitHub/angular/angular2-rxjs-chat/node_modules/extract-text-webpack-plugin/loader.js?{"omit":1,"extract":true,"remove":true}!style-loader!css-loader?sourceMap' },
        { test: /\.scss$/,
          loaders: 
           [ 'style-loader',
             '/Users/valilogi/GitHub/angular/angular2-rxjs-chat/node_modules/extract-text-webpack-plugin/loader.js?{"omit":1,"extract":true,"remove":true}!style-loader!css-loader?sourceMap',
             'sass-loader?outputStyle=expanded&root=/Users/valilogi/GitHub/angular/angular2-rxjs-chat/app&&includePaths[]/Users/valilogi/GitHub/angular/angular2-rxjs-chat/node_modules&&includePaths[]/Users/valilogi/GitHub/angular/angular2-rxjs-chat/app' ] },
        { test: /\.svg(\?v=\d+\.\d+\.\d+)?$/, loader: 'url-loader' },
        { test: /\.html$/, loader: 'raw' },
        { test: /^index\.html$/,
          loader: 'file-loader?name=[path][name].[ext]' },
        { test: /\.ts$/,
          loader: 'ts',
          exclude: [ /test/, /node_modules/ ] },
        { test: /vendor\/.*\.(css|js)/,
          loader: 'file-loader?name=[path][name].[ext]',
          exclude: [ /node_modules/ ] },
        { test: /\.woff(2)?(\?v=\d+\.\d+\.\d+)?$/,
          loader: 'file-loader?mimetype=application/font-woff&name=[path][name].[ext]' },
        { test: /\.ttf(\?v=\d+\.\d+\.\d+)?$/,
          loader: 'file-loader?mimetype=application/x-font-ttf&name=[path][name].[ext]' },
        { test: /\.eot(\?v=\d+\.\d+\.\d+)?\??$/,
          loader: 'file-loader?mimetype=application/vnd.ms-fontobject&name=[path][name].[ext]' },
        { test: /\.otf(\?v=\d+\.\d+\.\d+)?$/,
          loader: 'file-loader?mimetype=application/font-otf&name=[path][name].[ext]' },
        { test: /\.svg(\?v=\d+\.\d+\.\d+)?$/, loader: 'url-loader' } ],
     noParse: [ /\.min\.js/, /vendor[\/\\].*?\.(js|css)$/ ] },
  tslint: { emitErrors: false, failOnHint: false } }
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 127.0.0.1:8080
    at Object.exports._errnoException (util.js:1008:11)
    at exports._exceptionWithHostPort (util.js:1031:20)
    at Server._listen2 (net.js:1253:14)
    at listen (net.js:1289:10)
    at net.js:1399:9
    at GetAddrInfoReqWrap.asyncCallback [as callback] (dns.js:65:16)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:84:10)

npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "go"
npm ERR! node v6.3.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! angular2-rxjs-chat@1.0.0 go: `webpack-dev-server --display-reasons --display-chunks`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the angular2-rxjs-chat@1.0.0 go script 'webpack-dev-server --display-reasons --display-chunks'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular2-rxjs-chat package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack-dev-server --display-reasons --display-chunks
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular2-rxjs-chat
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular2-rxjs-chat
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/valilogi/GitHub/angular/angular2-rxjs-chat/npm-debug.log`

**Comment by webbiscuit** [comment]
Looks like you already have something listening on port 8080:

    Error: listen EADDRINUSE 127.0.0.1:8080

Either stop whatever that is, or change the port you're running the dev server on:

Looks like this line in webpack.config.js:

    entry.unshift("webpack-dev-server/client?http://"+reloadHost+":8080");

**Comment by vzairovlogi** [comment]
That helped :)
Thanks!
