### ISSUE TITLE
845 error 404 'angular' is not in the npm registry.

### ISSUE THREAD

**Issue by tempcke** [ng-book/angular2-rxjs-chat#29]
npm install seems to have issues on my system (linux mint 17.3)

among them:
845 error 404 'angular' is not in the npm registry.

full npm-debug.log: https://paste.ubuntu.com/23483699/

I admit I have almost no experience with nodejs but am hoping to change that soon.

**Comment by jashmenn** [comment]
I'm not exactly sure what's going on here. The @angular packages in the current version are correct. Feel free to reopen if this is happening to other people
