### ISSUE TITLE
webpack module resolution errors

### ISSUE THREAD

**Issue by philsurette** [ng-book/angular2-rxjs-chat#7]
I'm running under windows 7, working through ng-book2-r8, and would love to see this code in action. 

`npm install` seems to work fine. `npm run server` does not, it seems not to be able to work with many of the files referenced from `vendor.js`. I have no experience with webpack, not sure how to debug and the configuration is complex. When loading the page all I see is the Fork Me on Github image, and 404s for traceur, system, and angular2 scripts.

Output from webpack:

```
   [0] multi vendor 52 bytes {1} [built]
 [347] ./app/vendor.js 243 bytes {1} [built] [1 error]
 [348] ./vendor/traceur-runtime-0.0.87.js 46.7 kB {1} [built]
...
  [375] (webpack)/~/node-libs-browser/~/crypto-browserify/~/pbkdf2-compat/pbkdf2.js 2.06 kB {1} [built]
  [377] ./vendor/es6-module-loader@0.16.6.js 30.7 kB {1} [built] [2 errors]
  [378] ./vendor/es6-shim.js 117 kB {1} [optional] [built]
  [379] ./vendor/system-0.16.11.js 26.1 kB {1} [built] [1 error]
  [380] (webpack)/~/node-libs-browser/~/vm-browserify/index.js 3.8 kB {1} [built]
...
WARNING in ./vendor/traceur-runtime-0.0.87.js
Critical dependencies:
2:18427-18468 the request of a dependency is an expression
 @ ./vendor/traceur-runtime-0.0.87.js 2:18427-18468

WARNING in ./vendor/system-0.16.11.js
Critical dependencies:
5:1342-1349 require function is used in a way in which dependencies cannot be statically extracted
5:9069-9076 require function is used in a way in which dependencies cannot be statically extracted
 @ ./vendor/system-0.16.11.js 5:1342-1349 5:9069-9076

WARNING in ./vendor/es6-module-loader@0.16.6.js
Critical dependencies:
1:379-386 This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better results

 @ ./vendor/es6-module-loader@0.16.6.js 1:379-386

WARNING in ./vendor/angular2.dev.2.0.0-alpha.35.js
Critical dependencies:
19:113-120 This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better result
.
 @ ./vendor/angular2.dev.2.0.0-alpha.35.js 19:113-120

WARNING in ./vendor/angular2.dev.2.0.0-alpha.35.js
Critical dependencies:
2005:113-120 This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better resu
ts.
 @ ./vendor/angular2.dev.2.0.0-alpha.35.js 2005:113-120

WARNING in ./app/ts/components/ChatNavBar.ts
[18, 1]: exceeds maximum line length of 80


ERROR in ./vendor/bootstrap@3.3.5.min.css
Module parse failed: c:\dev\angular2\ngbook2\git\angular2-rxjs-chat\vendor\bootstrap@3.3.5.min.css Line 5: Unexpected token {

<<<deleted contents of css file output>>>

You may need an appropriate loader to handle this file type.@ ./app/vendor.js 5:0-41

ERROR in ./vendor/system-0.16.11.js
Module not found: Error: Cannot resolve module 'es6-module-loader' in C:\dev\angular2\ngbook2\code\rxjs\chat\vendor
 @ ./vendor/system-0.16.11.js 5:25146-25174

ERROR in ./vendor/es6-module-loader@0.16.6.js
Module not found: Error: Cannot resolve module 'when/es6-shim/Promise' in C:\dev\angular2\ngbook2\code\rxjs\chat\vendor
 @ ./vendor/es6-module-loader@0.16.6.js 1:21611-21643 1:26981-27013

ERROR in ./vendor/es6-module-loader@0.16.6.js
Module not found: Error: Cannot resolve module 'fs' in C:\dev\angular2\ngbook2\code\rxjs\chat\vendor
 @ ./vendor/es6-module-loader@0.16.6.js 1:27869-27882
```

Other info:

> npm -version
> 2.11.3

Other problems:
Microsoft visual code reports 5 errors in bootstrap@3.3.5.min.css, all \9's (messed up tabs I guess) in the minified file.

**Comment by viviancpy** [comment]
Samehere. npm install has no problem. but npm run server got the same error.
OS:Windows 8
npm -v:3.3.6

ERROR in ./vendor/system-0.16.11.js
Module not found: Error: Cannot resolve module 'es6-module-loader' in D:\code\angular2-rxjs-chat\vendor
 @ ./vendor/system-0.16.11.js 5:25146-25174

ERROR in ./vendor/bootstrap@3.3.5.min.css
Module parse failed: D:\code\angular2-rxjs-chat\vendor\bootstrap@3.3.5.min.css Line 5: Unexpected token {
You may need an appropriate loader to handle this file type.
|  * Copyright 2011-2015 Twitter, Inc.
|  * Licensed under MIT (https://github.com/twbs/bootstrap/blob/master/LICENSE)
|  *//*! normalize.css v3.0.3 | MIT License | github.com/necolas/normalize.css */html{font-family:sans-serif;-webkit-te
<<viviancpy: css deleted>>
ERROR in ./vendor/es6-module-loader@0.16.6.js
Module not found: Error: Cannot resolve module 'when/es6-shim/Promise' in D:\code\angular2-rxjs-chat\vendor
 @ ./vendor/es6-module-loader@0.16.6.js 1:21611-21643 1:26981-27013

ERROR in ./vendor/es6-module-loader@0.16.6.js
Module not found: Error: Cannot resolve module 'fs' in D:\code\angular2-rxjs-chat\vendor
 @ ./vendor/es6-module-loader@0.16.6.js 1:27869-27882

**Comment by drumc** [comment]
exact same issues here also.  running node v 0.12.0 and can't get the webpack dev server to work.  issues with the minified bootstrap and es6 module loader

**Comment by jashmenn** [comment]
I just pushed a change that should help it to work on windows. See: https://github.com/ng-book/angular2-rxjs-chat/commit/b1fb9573aafccfcccf4c5ddc164a4395cffbdce2 - I believe the issue was that we were using forward-slashes for paths which won't work in windows.

Another thing to try might be running it in Cygwin.
